### ISSUE TITLE
Crash on empty file

### ISSUE THREAD

**Issue by alexjurkiewicz** [awslabs/cfn-python-lint#104]
```
$ touch foo
$ cfn-lint --template foo
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/cfnlint/__main__.py", line 27, in main
    (args, template, rules, fmt, formatter) = cfnlint.core.get_template_args_rules(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/cfnlint/core.py", line 207, in get_template_args_rules
    defaults = get_default_args(template)
  File "/usr/local/lib/python2.7/site-packages/cfnlint/core.py", line 279, in get_default_args
    if isinstance(configs, dict):
UnboundLocalError: local variable 'configs' referenced before assignment
```

**Comment by kddejong** [comment]
Released with the  newest version.
