### ISSUE TITLE
VSCode - The CloudFormation linter Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by reidca** [awslabs/cfn-python-lint#161]
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 16:46:36] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 16:46:37] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 16:46:37] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 16:46:37] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cfn-lint ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error - 16:46:37] Connection to server got closed. Server will not be restarted.

**Comment by fatbasstard** [comment]
Do you have cfn-lint installed(system-wide) as a standalone application? As describred here: https://github.com/awslabs/cfn-python-lint#pip-install

I've seen this before. Maybe the error handling is not very "intuitive", but that might be worth an issue in https://github.com/awslabs/aws-cfn-lint-visual-studio-code.

I'll add an issue there for this

**Comment by cmmeyer** [comment]
Issue moved to the VS Code plugin:
awslabs/aws-cfn-lint-visual-studio-code#9

Closing issue here.
