### ISSUE TITLE
Undocumented dependencies. Require a ~/.aws/config

### ISSUE THREAD

**Issue by DavidOpVa** [awslabs/cfn-python-lint#253]
*cfn-lint version: cfn-lint 0.3.2 and 0.4.2 (at least)*

*Description of issue.*
cfn-lint have an undocumented dependencies to the .aws/config file. (You have to run aws configure in order to run cfn-lint).

Otherwise, it fails with these error : 
Traceback (most recent call last):
  File "/{anonPath}/venv/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/{anonPath}/venv/lib/python3.6/site-packages/cfnlint/__main__.py", line 33, in main
    args.override_spec, formatter))
  File "/{anonPath}/venv/lib/python3.6/site-packages/cfnlint/core.py", line 53, in run_cli
    matches = run_checks(filename, template, rules, regions)
  File "/{anonPath}/venv/lib/python3.6/site-packages/cfnlint/core.py", line 312, in run_checks
    matches.extend(runner.transform())
  File "/{anonPath}/venv/lib/python3.6/site-packages/cfnlint/__init__.py", line 807, in transform
    matches = transform.transform_template()
  File "/{anonPath}/venv/lib/python3.6/site-packages/cfnlint/transform.py", line 106, in transform_template
    sam_translator.translate(sam_template=self._template, parameter_values={})
  File "/{anonPath}/venv/lib/python3.6/site-packages/samtranslator/translator/translator.py", line 57, in translate
    deployment_preference_collection = DeploymentPreferenceCollection()
  File "/{anonPath}/venv/lib/python3.6/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 30, in __init__
    self.codedeploy_iam_role = self._codedeploy_iam_role()
  File "/{anonPath}/venv/lib/python3.6/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 89, in _codedeploy_iam_role
    ArnGenerator.generate_aws_managed_policy_arn('service-role/AWSCodeDeployRoleForLambda')
  File "/{anonPath}/venv/lib/python3.6/site-packages/samtranslator/translator/arn_generator.py", line 22, in generate_aws_managed_policy_arn
    return 'arn:{}:iam::aws:policy/{}'.format(ArnGenerator.get_partition_name(),
  File "/{anonPath}/venv/lib/python3.6/site-packages/samtranslator/translator/arn_generator.py", line 44, in get_partition_name
    region_string = region.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

Specifying a region with -r in cfn lint doesnt fix the issue.

**Comment by kddejong** [comment]
Shoot. It’s the AWS SAM package we use to transform servlerless templates.  I thought we had worked a way around this. Let us see if we can do anything there. Our goal has always been to not rely on a network connection to lint.  I would like to also not require that file but need to do some digging. Thanks for pointing this out.

**Comment by DavidOpVa** [comment]
I followed it to SAM too.
I have been able to workaround it by setting an environment variable 
AWS_DEFAULT_REGION which will be taken as value if there is no region precised (if i understand correctly the SAM code)

**Comment by cmmeyer** [comment]
I feel like there's been a discussion on the SAM side about defaulting to us-east-1.  Let me see if I can dig up the issue on their side.

**Comment by fatbasstard** [comment]
I'll see if we can work around this, or pass along the `cfn-lint` region to SAM.

**Comment by fatbasstard** [comment]
Ah, remember this indeed, I'll add a ticket/PR in SAM.

Issue is in this lineL https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/translator/arn_generator.py#L39

If no region is specified is uses Boto to load it. Which uses the "default" aws configuration for this. That method has Region as an input parameter, but in the calling method above (https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/translator/arn_generator.py#L22) it never passes the region.

I'll see if I can open up the flow in this process so we can actually pass along the region

**Comment by fatbasstard** [comment]
A workaround based on the SAM code could be using an Environment Variable (`AWS_DEFAULT_REGION`)

**Comment by fatbasstard** [comment]
@kddejong In what extend is setting the environment variable in the linter an option?

**Comment by kddejong** [comment]
good question @fatbasstard I would need to do some more research on that but I would think if it isn't set and it wouldn't be intrusive maybe we can set it for them... at least to  use the Transform functionality for SAM.

**Comment by kddejong** [comment]
Fixed in v0.5.0.  Please validate and we can re-open if needed.
