### ISSUE TITLE
Crash with malformed templates not containing YAML maps

### ISSUE THREAD

**Issue by adamchainz** [awslabs/cfn-python-lint#322]
*cfn-lint version: (`cfn-lint --version`)* 0.6.1

*Description of issue.*

```
$ echo malformed > test.yml
$ cfn-lint test.yml
Traceback (most recent call last):
  File "/Users/myusername/.virtualenvs/myvirtualenv/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/myusername/.virtualenvs/myvirtualenv/lib/python3.7/site-packages/cfnlint/__main__.py", line 27, in main
    (args, filename, template, rules, fmt, formatter) = cfnlint.core.get_template_args_rules(sys.argv[1:])
  File "/Users/myusername/.virtualenvs/myvirtualenv/lib/python3.7/site-packages/cfnlint/core.py", line 222, in get_template_args_rules
    for section, values in get_default_args(template).items():
  File "/Users/myusername/.virtualenvs/myvirtualenv/lib/python3.7/site-packages/cfnlint/core.py", line 258, in get_default_args
    if isinstance(configs, dict):
UnboundLocalError: local variable 'configs' referenced before assignment
```

This doesn't work if I instead do `echo '{}' > test.yml`, but does with `echo 1 > test.yml` and `echo [] > test.yml`, so it seems to be a problem with the type of the object in the template.

**Comment by cmmeyer** [comment]
It looks like the string in the file is being decoded as valid and passed into the config parser to start looking at the (non-existent) meta-data:

https://github.com/awslabs/cfn-python-lint/blob/38b0f23a319eddd9b94dc9e2649c64b96775214e/src/cfnlint/core.py#L223-L225

https://github.com/awslabs/cfn-python-lint/blob/38b0f23a319eddd9b94dc9e2649c64b96775214e/src/cfnlint/core.py#L223-L225

We'll need better error trapping when we attempt to extract values from the config section
