### ISSUE TITLE
Tests fail out of box with ModuleNotFoundError: No module named 'awscli'

### ISSUE THREAD

**Issue by rjlohan** [awslabs/cfn-python-lint#418]
*cfn-lint version: (`cfn-lint --version`)* 0.8.2

*Description of issue.* 

Out of box, the `tox` tests do not pass on my developer box due to a module import error; 
```
ImportError: Failed to import test module: module.test_string_template
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/Users/ryanloha/workspaces/cfn-python-lint/test/module/test_string_template.py", line 19, in <module>
    from cfnlint.core import DEFAULT_RULESDIR  # pylint: disable=E0401
  File "/Users/ryanloha/workspaces/cfn-python-lint/.tox/py37/lib/python3.7/site-packages/cfnlint/core.py", line 22, in <module>
    from awscli.help import LOG
ModuleNotFoundError: No module named 'awscli'
```

Not sure why this tool even has a dependency on `awscli`, I assume it's indirectly via SAM? (Though I found at least one direct, though unused, import from `awscli.help`

**Comment by rjlohan** [comment]
Ignore me, I think I have a PEBCAK issue.

**Comment by cmmeyer** [comment]
Cool. I notice above you're using python 3.7 as your base version (brew seems to have moved on from 3.6).  We may need to start including 3.7 in our test runs.
