### ISSUE TITLE
Invalid PrimaryKey attribute crashes cfn-lint  instead of raising lint error.

### ISSUE THREAD

**Issue by emilbryggare** [awslabs/cfn-python-lint#436]
Hi AWS,

I found a minor bug on cfn-lint version: cfn-lint 0.8.3

An attribute in Resource -> Properties-> PrimaryKey leads to crash instead of a raised lint error

Here is a sample template. If  MyInvalidAttr is replaced with a correct attribute eg Name then the template works.
```AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MyTable
      PrimaryKey:
        MyInvalidAttr: id
        Type: String
```
Below is the error:
```
$ cfn-lint -t template.yaml
Traceback (most recent call last):
  File "/Users/emilbryggare/Library/Python/2.7/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/cfnlint/__main__.py", line 36, in main
    args.regions, args.override_spec))
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/cfnlint/core.py", line 46, in run_cli
    return run_checks(filename, template, rules, regions)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/cfnlint/core.py", line 316, in run_checks
    matches.extend(runner.transform())
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/cfnlint/__init__.py", line 894, in transform
    matches = transform.transform_template()
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/cfnlint/transform.py", line 115, in transform_template
    sam_translator.translate(sam_template=self._template, parameter_values={}))
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/translator/translator.py", line 72, in translate
    translated = macro.to_cloudformation(**kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/model/sam_resources.py", line 537, in to_cloudformation
    dynamodb_resources = self._construct_dynamodb_table()
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/model/sam_resources.py", line 546, in _construct_dynamodb_table
    'AttributeName': self.PrimaryKey['Name'],
KeyError: 'Name'
```

**Comment by kddejong** [comment]
@emilbryggare We will now catch all exceptions from SAM.  Did you happen to submit a similar issue to SAM for this error?  This should have been caught on their side too.

**Comment by emilbryggare** [comment]
@kddejong great work! No, just submitted it here. 
Should I do it so they can catch it as well?

**Comment by kddejong** [comment]
if you could that would be great.  Thanks.
